theme: jekyll-dash

title: hlindqvist
author: Håkan Lindqvist
email: hawk@qw.se
description: > # this means to ignore newlines until "show_exerpts:"
  Håkan is a software engineer and DNS fanatic living in Sweden.
  He occasionally blogs about software, networking and related topics.
show_excerpts: false # set to true to show excerpts on the homepage

# required by disqus to display comments
url: https://hakanlindqvist.com


# jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"

# jekyll-tagging (optional)
tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# for github pages custom domains:
include: [CNAME]

#plugins: [jekyll-paginate]

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - jekyll/tagging


dash:
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"

  # (optional) discqus comment configuration
  #disqus:
  #  shortname: <your-disqus-shortname>

  # the animation speed of the post scroll-in effect
  animation_speed: 50

  # wether to enable Right-to-Left support or not
  rtl: false

  # Replaces the default avatar provider (gravatar)
  avatar_source: github
  github_username: hlindqvist
  #avatar_source: local
  #avatar_path: /assets/avatar.png

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://noc.social/@hlindqvist
      icon: mastodon
      color: purple
      rel: me
    - url: https://github.com/hlindqvist
      icon: github
      color: indigo
      rel: me
    - url: https://twitter.com/HakanLindqvist
      icon: twitter
      color: cyan
      rel: me

  # wether the author box should be displayed or not
  show_author: true
