theme: jekyll-theme-hacker
title: hakanlindqvist.com
name: Håkan Lindqvist
author: Håkan Lindqvist
description: insert description here
google_analytics: UA-57946803-1

paginate: 2
paginate_path: "/blog/page:num/"
